const URL_ENDPOINTS = {
  GET_ABOUT_US: 'get-about-us',
  EDIT_ABOUT_US: 'edit-about-us',
  GET_ALL_ARTICLES: 'get-all-articles',
  ADD_ARTICLE: 'post-article',
  EDIT_ARTICLE: 'edit-article',
  DELETE_ARTICLE: 'delete-article',
  GET_ALL_SERVICES: 'get-all-services',
  ADD_SERVICE: 'post-service',
  EDIT_SERVICE: 'edit-service-by-id',
  DELETE_SERVICE: 'delete-service',
  GET_USER_INFO: 'user_info',
  GET_BUSINESS_INFO: 'get_business',
  LOGIN_PHYSIC: 'login',
  LOGIN_BUSINESS: 'login_business',
  CHANGE_EMAIL: 'change_email',
  CHANGE_PASSWORD: 'change_password',
  SEND_FORM: 'send_form',
  GET_EMPLOYEES: 'workers/get_all_workers',
  GET_EMPLOYEE_INFO: 'workers/worker_info',
  ADD_EMPLOYEE: 'workers/create_worker',
  REMOVE_EMPLOYEE: 'workers/delete_worker',
  EDIT_EMPLOYEE: 'workers/edit_worker',
  GET_SUSP_CHECKS: 'suspicious_validations',
  GET_CLIENTS_PAGE: 'get_related_physics',
  GET_CHECKS: 'get_all_validations',
  GET_CHECK_LOG: 'get_validation_logs',
  SUMBIT_CHECK: 'new_validation',
  GET_METERS: 'get_transactions_logs',
  GET_SUSP_METERS: 'get_suspicious_transactions_logs',
  SAVE_FILE: 'save_file',
};

const SYSTEM_MESSAGES = {
  LOGIN_SCSS: 'Вы успешно авторизовались в учетной записи',
  LOGIN_FAIL:
    'В системе нет пользователя с таким именем пользователя и паролем',
  UPD_ABOUT_SCSS: 'Описание успешно обновлено',
  UPD_ABOUT_FAIL: 'Ошибка при попытке обновить данные на сервере',
  LOGOUT_SCSS: 'Пользователь успешно вышел из аккаунта',
  SERVICE_ADD_SCSS: 'Услуга успешно добавлена',
  SERVICE_ADD_FAIL: 'Ошибка при попытке создания услуги на сервере',
  SERVICE_REMOVE_SCSS: 'Услуга успешно удалена',
  SERVICE_REMOVE_FAIL: 'Ошибка при попытке удаления услуги на сервере',
  SERVICE_EDIT_SCSS: 'Услуга успешно изменена',
  SERVICE_EDIT_FAIL: 'Ошибка при попытке редактирования услуги на сервере',
  USER_DATA_UPD_SCSS: 'Данные пользователя успешно обновлены',
  EMAIL_UPD_SCSS: 'Адрес электронной почты успешно обновлён',
  PASSWORD_UPD_SCSS: 'Пароль пользователя успешно обновлён',
  USER_DATA_UPD_FAIL:
    'Ошибка при попытке обновления данных пользователя на сервере',
  EMAIL_UPD_FAIL:
    'Ошибка при попытке обновления адреса электронной почты на сервере',
  PASSWORD_UPD_FAIL: 'Ошибка при попытке обновления пароля на сервере',
  SEND_FORM_ERROR:
    'Ошибка при попытке отправить форму, пожалуйста попробуйте еще раз',
  SEND_FORM_SCSS:
    'Спасибо, Ваше сообщение отправлено. Мы рассмотрим его и свяжемся с Вами',
  FORGOT_PASSWORD_ALERT:
    'Обратитесь в службу поддержки для восстановления пароля',
  TOKEN_EXPIRED: 'Ваш ключ устарел. Авторизуйтесь в приложении снова',
  GET_EMPLOYEES_FAIL: 'Ошибка при получении данных сотрудников с сервера',
  ADD_EMPLOYEE_SCSS: 'Новый сотрудник успешно добавлен',
  ADD_EMPLOYEE_FAIL: 'Ошибка при добавлении нового сотрудника',
  REMOVE_EMPLOYEE_SCSS: 'Карточка сотрудника успешно удалена',
  REMOVE_EMPLOYEE_FAIL: 'Ошибка при удалении карточки сотрудника',
  EDIT_EMPLOYEE_SCSS: 'Карточка сотрудника успешно изменена',
  EDIT_EMPLOYEE_FAIL: 'Ошибка при изменении карточки сотрудника',
  GET_CLIENTS_FAIL: 'Ошибка при получении списка абонентов',
  GET_CHECKS_FAIL: 'Ошибка при получении результатов проверки',
  GET_METERS_FAIL: 'Ошибка при получении показаний клиентов',
  ERROR_401: 'Возникла проблема с авторизацией',
  ERROR_400_412: 'Для выполнения операции авторизуйтесь как юридическое лицо',
  ERROR_402: 'Сотрудник с таким логином или именем уже существует',
  ERROR_404: 'По вашему запросу ничего не найдено',
  DOWNLOAD_ERROR: 'Ошибка при скачивании файла',
  DOWNLOAD_SCSS: 'Файл успешно сохранён',
};
export { URL_ENDPOINTS, SYSTEM_MESSAGES };
